// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD21pTfLCQRk7xhdLERGRfJnAmOuhQ_z-8',
    appId: '1:1079414262963:web:9c20735c3c9da77f8cf4c6',
    messagingSenderId: '1079414262963',
    projectId: 'senior-ade3b',
    authDomain: 'senior-ade3b.firebaseapp.com',
    storageBucket: 'senior-ade3b.firebasestorage.app',
    measurementId: 'G-XTZ8N8R29V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyqCmLvG7toljqG6H7hoAvWivotq1MV7c',
    appId: '1:1079414262963:android:1da3907e2e1a781b8cf4c6',
    messagingSenderId: '1079414262963',
    projectId: 'senior-ade3b',
    storageBucket: 'senior-ade3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXGEMiBddfB2vR7sdYMazoL1xnDrP3vZY',
    appId: '1:1079414262963:ios:a0959fd227e984358cf4c6',
    messagingSenderId: '1079414262963',
    projectId: 'senior-ade3b',
    storageBucket: 'senior-ade3b.firebasestorage.app',
    iosBundleId: 'com.example.senior',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXGEMiBddfB2vR7sdYMazoL1xnDrP3vZY',
    appId: '1:1079414262963:ios:a0959fd227e984358cf4c6',
    messagingSenderId: '1079414262963',
    projectId: 'senior-ade3b',
    storageBucket: 'senior-ade3b.firebasestorage.app',
    iosBundleId: 'com.example.senior',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD21pTfLCQRk7xhdLERGRfJnAmOuhQ_z-8',
    appId: '1:1079414262963:web:c0617862d7d9166c8cf4c6',
    messagingSenderId: '1079414262963',
    projectId: 'senior-ade3b',
    authDomain: 'senior-ade3b.firebaseapp.com',
    storageBucket: 'senior-ade3b.firebasestorage.app',
    measurementId: 'G-RWGKSXJ7BF',
  );
}
